FROM openjdk:17-ea-slim-buster

ADD ./build/libs/ATP_Back-0.0.1-SNAPSHOT.jar /app.jar

ENV FILEPATH=/images

EXPOSE 8080

CMD ["java", "-jar", "/app.jar", "-Dfile.encoding=UTF-8", "-Dconsole.encoding=UTF-8"]