spring:
  web:
    cors:
      allowed-origins: "https://celarim.kro.kr:443" # 프론트엔드 URL을 설정
      allowed-methods: "*"
      allowed-headers: "*"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG

jwtData:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
filepath:
  default: ${FILEPATH}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
