server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mariadb://${DB_URL}:3306/atp?protocol=tcp&useHostsInPrivileges=true"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    mongodb:
      uri: "mongodb+srv://${MONGODB_ID}:${MONGODB_PASS}@cluster0.e5il1.mongodb.net/americastock?retryWrites=true&w=majority&appName=Cluster0"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG

jwtData:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
filepath:
  default: ${FILEPATH}

url: ${SERVER_URL}