server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mariadb://database-xena.cr2awsc2ysrw.ap-northeast-2.rds.amazonaws.com:3306/atp?protocol=tcp&useHostsInPrivileges=true"
    username: admin
    password: fowltm556
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    mongodb:
      uri: "mongodb+srv://atpadmin:4JTBTOqa3qWcUPSO@cluster0.e5il1.mongodb.net/americastock?retryWrites=true&w=majority&appName=Cluster0"
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG

jwtData:
  secret: acbdegfhikjlmonpqsrtuwvxzy0123456789acbdegfhikjlmonpqsrtuwvxzy0123456789
  expiration: 86400000
filepath:
  default: "."

url: atp.xena.p-e.kr